import {
  ArrowRight,
  ArrowUpRight,
  Award,
  Book,
  Bookmark,
  Check,
  ChevronDown,
  Circle,
  CircleCheck,
  Clock,
  Filter,
  Globe,
  GraduationCap,
  Grid3X3,
  Handshake,
  Heart,
  HeartPulse,
  Image as ImageIcon,
  Info,
  Leaf,
  Link2,
  Mail,
  MapPin,
  Menu,
  Newspaper,
  Phone,
  Play,
  Plus,
  Rows3,
  Send,
  Target,
  Trophy,
  Upload,
  UserPlus,
  Users,
  Video,
  Vote,
  X,
} from 'lucide-react';

const iconMap = {
  'arrow-right': ArrowRight,
  'arrow-up-right': ArrowUpRight,
  award: Award,
  book: Book,
  bookmark: Bookmark,
  check: Check,
  'check-circle': CircleCheck,
  'chevron-down': ChevronDown,
  clock: Clock,
  filter: Filter,
  globe: Globe,
  'graduation-cap': GraduationCap,
  'grid-3x3': Grid3X3,
  handshake: Handshake,
  heart: Heart,
  'heart-pulse': HeartPulse,
  image: ImageIcon,
  info: Info,
  leaf: Leaf,
  'link-2': Link2,
  mail: Mail,
  'map-pin': MapPin,
  menu: Menu,
  newspaper: Newspaper,
  phone: Phone,
  play: Play,
  plus: Plus,
  'rows-3': Rows3,
  send: Send,
  target: Target,
  trophy: Trophy,
  upload: Upload,
  'user-plus': UserPlus,
  users: Users,
  video: Video,
  vote: Vote,
  x: X,
};

export default function Icon({ i, size = 20, strokeWidth = 2, ...props }) {
  const LucideIcon = iconMap[i] || Circle;
  return <LucideIcon size={size} strokeWidth={strokeWidth} aria-hidden="true" {...props} />;
}
